[package]
name = "web_audio_converter"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["serde_json", "json"] }
thiserror = "2.0.11"
serde = "1.0.217"
symphonia = { version = "0.5.4", features = ["all", "opt-simd"] }
base64 = "0.22.1"
